<?php namespace App\Database\Migrations;

class CreateSystemSettingsPermissions extends \CodeIgniter\Database\Migration {

    private $table = 'permissions';

    public function up()
    {
      $data = [
        [
            'function_name' => 'list of conditions',
            'function_description' => 'list of conditions',
            'slugs' => 'list-condition',
            'name_on_class' => 'index',
            'page_title' => 'list of conditions',
            'module_id' => '1',
            'link_icon' => '<i class="fas fa-child"></i>',
            'order' => '1',
            'table_name' => 'conditions',
            'func_action' => 'link',
            'func_type' => 1,
            'allowed_roles' => "[1]",
            'status' => 'a',
            'created_at' => date('Y-m-d H:i:s')
        ],
        [
            'function_name' => 'add conditions',
            'function_description' => 'add conditions',
            'slugs' => 'add-condition',
            'name_on_class' => 'add_condition',
            'page_title' => 'add conditions',
            'module_id' => '1',
            'link_icon' => '',
            'order' => '2',
            'table_name' => 'conditions',
            'func_action' => 'add',
            'func_type' => 3,
            'allowed_roles' => "[1]",
            'status' => 'a',
            'created_at' => date('Y-m-d H:i:s')
        ],
        [
            'function_name' => 'delete conditions',
            'function_description' => 'delete conditions',
            'slugs' => 'delete-condition',
            'name_on_class' => 'delete_condition',
            'page_title' => 'delete conditions',
            'module_id' => '1',
            'link_icon' => '',
            'order' => '3',
            'table_name' => 'conditions',
            'func_action' => 'delete',
            'func_type' => 3,
            'allowed_roles' => "[1]",
            'status' => 'a',
            'created_at' => date('Y-m-d H:i:s')
        ],
        [
            'function_name' => 'edit conditions',
            'function_description' => 'edit conditions',
            'slugs' => 'edit-condition',
            'name_on_class' => 'edit_condition',
            'page_title' => 'edit conditions',
            'module_id' => '1',
            'link_icon' => '',
            'order' => '4',
            'table_name' => 'conditions',
            'func_action' => 'edit',
            'func_type' => 3,
            'allowed_roles' => "[1]",
            'status' => 'a',
            'created_at' => date('Y-m-d H:i:s')
        ],
        [
            'function_name' => 'list of allergy',
            'function_description' => 'list of allergy',
            'slugs' => 'list-allergy',
            'name_on_class' => 'index',
            'page_title' => 'list of allergy',
            'module_id' => '1',
            'link_icon' => '<i class="fas fa-allergies"></i>',
            'order' => '5',
            'table_name' => 'allergies',
            'func_action' => 'link',
            'func_type' => 1,
            'allowed_roles' => "[1]",
            'status' => 'a',
            'created_at' => date('Y-m-d H:i:s')
        ],
        [
            'function_name' => 'add allergy',
            'function_description' => 'add allergy',
            'slugs' => 'add-allergy',
            'name_on_class' => 'add_allergy',
            'page_title' => 'add allergy',
            'module_id' => '1',
            'link_icon' => '',
            'order' => '6',
            'table_name' => 'allergies',
            'func_action' => 'add',
            'func_type' => 3,
            'allowed_roles' => "[1]",
            'status' => 'a',
            'created_at' => date('Y-m-d H:i:s')
        ],
        [
            'function_name' => 'delete allergy',
            'function_description' => 'delete allergy',
            'slugs' => 'delete-allergy',
            'name_on_class' => 'delete_allergy',
            'page_title' => 'delete allergy',
            'module_id' => '1',
            'link_icon' => '',
            'order' => '7',
            'table_name' => 'allergies',
            'func_action' => 'delete',
            'func_type' => 3,
            'allowed_roles' => "[1]",
            'status' => 'a',
            'created_at' => date('Y-m-d H:i:s')
        ],
        [
            'function_name' => 'edit allergy',
            'function_description' => 'edit allergy',
            'slugs' => 'edit-allergy',
            'name_on_class' => 'edit_allergy',
            'page_title' => 'edit allergy',
            'module_id' => '1',
            'link_icon' => '',
            'order' => '8',
            'table_name' => 'allergies',
            'func_action' => 'edit',
            'func_type' => 3,
            'allowed_roles' => "[1]",
            'status' => 'a',
            'created_at' => date('Y-m-d H:i:s')
        ],

        [
            'function_name' => 'list of allergy type',
            'function_description' => 'list of allergy type',
            'slugs' => 'list-allergy-type',
            'name_on_class' => 'index',
            'page_title' => 'list of allergy type',
            'module_id' => '1',
            'link_icon' => '<i class="fas fa-allergies"></i>',
            'order' => '9',
            'table_name' => 'allergy_types',
            'func_action' => 'link',
            'func_type' => 1,
            'allowed_roles' => "[1]",
            'status' => 'a',
            'created_at' => date('Y-m-d H:i:s')
        ],
        [
            'function_name' => 'add allergy type',
            'function_description' => 'add allergy type',
            'slugs' => 'add-allergy-type',
            'name_on_class' => 'add',
            'page_title' => 'add allergy type',
            'module_id' => '1',
            'link_icon' => '',
            'order' => '10',
            'table_name' => 'allergy_types',
            'func_action' => 'add',
            'func_type' => 3,
            'allowed_roles' => "[1]",
            'status' => 'a',
            'created_at' => date('Y-m-d H:i:s')
        ],
        [
            'function_name' => 'delete allergy type',
            'function_description' => 'delete allergy type',
            'slugs' => 'delete-allergy-type',
            'name_on_class' => 'delete',
            'page_title' => 'delete allergy type',
            'module_id' => '1',
            'link_icon' => '',
            'order' => '11',
            'table_name' => 'allergy_types',
            'func_action' => 'delete',
            'func_type' => 3,
            'allowed_roles' => "[1]",
            'status' => 'a',
            'created_at' => date('Y-m-d H:i:s')
        ],
        [
            'function_name' => 'edit allergy type',
            'function_description' => 'edit allergy type',
            'slugs' => 'edit-allergy-type',
            'name_on_class' => 'edit',
            'page_title' => 'edit allergy type',
            'module_id' => '1',
            'link_icon' => '',
            'order' => '12',
            'table_name' => 'allergy_types',
            'func_action' => 'edit',
            'func_type' => 3,
            'allowed_roles' => "[1]",
            'status' => 'a',
            'created_at' => date('Y-m-d H:i:s')
        ],

        [
            'function_name' => 'list of reaction',
            'function_description' => 'list of reaction',
            'slugs' => 'list-reaction',
            'name_on_class' => 'index',
            'page_title' => 'list of reaction',
            'module_id' => '1',
            'link_icon' => '<i class="fas fa-child"></i>',
            'order' => '13',
            'table_name' => 'reactions',
            'func_action' => 'link',
            'func_type' => 1,
            'allowed_roles' => "[1]",
            'status' => 'a',
            'created_at' => date('Y-m-d H:i:s')
        ],
        [
            'function_name' => 'add reaction',
            'function_description' => 'add reaction',
            'slugs' => 'add-reaction',
            'name_on_class' => 'add',
            'page_title' => 'add reaction',
            'module_id' => '1',
            'link_icon' => '',
            'order' => '14',
            'table_name' => 'reactions',
            'func_action' => 'add',
            'func_type' => 3,
            'allowed_roles' => "[1]",
            'status' => 'a',
            'created_at' => date('Y-m-d H:i:s')
        ],
        [
            'function_name' => 'delete reaction',
            'function_description' => 'delete reaction',
            'slugs' => 'delete-reaction',
            'name_on_class' => 'delete',
            'page_title' => 'delete reaction',
            'module_id' => '1',
            'link_icon' => '',
            'order' => '15',
            'table_name' => 'reactions',
            'func_action' => 'delete',
            'func_type' => 3,
            'allowed_roles' => "[1]",
            'status' => 'a',
            'created_at' => date('Y-m-d H:i:s')
        ],
        [
            'function_name' => 'edit reaction',
            'function_description' => 'edit reaction',
            'slugs' => 'edit-reaction',
            'name_on_class' => 'edit',
            'page_title' => 'edit reaction',
            'module_id' => '1',
            'link_icon' => '',
            'order' => '16',
            'table_name' => 'reactions',
            'func_action' => 'edit',
            'func_type' => 3,
            'allowed_roles' => "[1]",
            'status' => 'a',
            'created_at' => date('Y-m-d H:i:s')
        ],
      ];

      $db      = \Config\Database::connect();
      $builder = $db->table($this->table);
      $builder->insertBatch($data);
    }

    public function down(){

    }
}
