<?php namespace App\Database\Migrations;

class CreatePatientPermissions extends \CodeIgniter\Database\Migration {

        private $table = 'permissions';
        public function up()
        {
                  $data = [
                      [
                          'function_name' => 'show patient details',
                          'function_description' => 'show patient details',
                          'slugs' => 'show-patient',
                          'name_on_class' => 'show_patient',
                          'page_title' => 'patient details',
                          'module_id' => '3',
                          'link_icon' => '',
                          'order' => '2',
                          'table_name' => 'patients',
                          'func_action' => 'show',
                          'func_type' => 3,
                          'allowed_roles' => "[1]",
                          'status' => 'a',
                          'created_at' => date('Y-m-d H:i:s')
                      ],
                      [
                          'function_name' => 'create patient',
                          'function_description' => 'create patient',
                          'slugs' => 'add-patient',
                          'name_on_class' => 'add_patient',
                          'page_title' => 'create a patient',
                          'module_id' => '3',
                          'link_icon' => '',
                          'order' => '3',
                          'table_name' => 'patients',
                          'func_action' => 'add',
                          'func_type' => 3,
                          'allowed_roles' => "[1]",
                          'status' => 'a',
                          'created_at' => date('Y-m-d H:i:s')
                      ],
                      [
                          'function_name' => 'list of patients',
                          'function_description' => 'patients',
                          'slugs' => 'list-patient',
                          'name_on_class' => 'index',
                          'page_title' => 'list of patients',
                          'module_id' => '3',
                          'link_icon' => '<i class="fas fa-users"></i>',
                          'order' => '4',
                          'table_name' => 'patients',
                          'func_action' => 'link',
                          'func_type' => 1,
                          'allowed_roles' => "[1]",
                          'status' => 'a',
                          'created_at' => date('Y-m-d H:i:s')
                      ],
                      [
                          'function_name' => 'edit patient',
                          'function_description' => 'edit patient',
                          'slugs' => 'edit-patient',
                          'name_on_class' => 'edit_patient',
                          'page_title' => 'edit patient',
                          'module_id' => '3',
                          'link_icon' => '',
                          'order' => '5',
                          'table_name' => 'patients',
                          'func_action' => 'edit',
                          'func_type' => 3,
                          'allowed_roles' => "[1]",
                          'status' => 'a',
                          'created_at' => date('Y-m-d H:i:s')
                      ],
                      [
                          'function_name' => 'delete patient',
                          'function_description' => 'delete patient',
                          'slugs' => 'delete-patient',
                          'name_on_class' => 'delete_patient',
                          'page_title' => 'delete patient',
                          'module_id' => '3',
                          'link_icon' => '',
                          'order' => '6',
                          'table_name' => 'patients',
                          'func_action' => 'delete',
                          'func_type' => 3,
                          'allowed_roles' => "[1]",
                          'status' => 'a',
                          'created_at' => date('Y-m-d H:i:s')
                      ],
                      [
                          'function_name' => 'create patient condition',
                          'function_description' => 'create patient condition',
                          'slugs' => 'add-patient-condition',
                          'name_on_class' => 'add',
                          'page_title' => 'create a patient condition',
                          'module_id' => '3',
                          'link_icon' => '',
                          'order' => '7',
                          'table_name' => 'patient_conditions',
                          'func_action' => 'add',
                          'func_type' => 3,
                          'allowed_roles' => "[1]",
                          'status' => 'a',
                          'created_at' => date('Y-m-d H:i:s')
                      ],
                      [
                          'function_name' => 'list of patient conditions',
                          'function_description' => 'patients',
                          'slugs' => 'list-patient-condition',
                          'name_on_class' => 'index',
                          'page_title' => 'list of patients conditions',
                          'module_id' => '3',
                          'link_icon' => '<i class="fas fa-users"></i>',
                          'order' => '8',
                          'table_name' => 'patient_conditions',
                          'func_action' => 'link',
                          'func_type' => 2,
                          'allowed_roles' => "[1]",
                          'status' => 'a',
                          'created_at' => date('Y-m-d H:i:s')
                      ],
                      [
                          'function_name' => 'edit patient condition',
                          'function_description' => 'edit patient condition',
                          'slugs' => 'edit-patient-condition',
                          'name_on_class' => 'edit',
                          'page_title' => 'edit patient condition',
                          'module_id' => '3',
                          'link_icon' => '',
                          'order' => '9',
                          'table_name' => 'patient_conditions',
                          'func_action' => 'edit',
                          'func_type' => 3,
                          'allowed_roles' => "[1]",
                          'status' => 'a',
                          'created_at' => date('Y-m-d H:i:s')
                      ],
                      [
                          'function_name' => 'delete patient condition',
                          'function_description' => 'delete patient condition',
                          'slugs' => 'delete-patient-condition',
                          'name_on_class' => 'delete',
                          'page_title' => 'delete patient condition',
                          'module_id' => '3',
                          'link_icon' => '',
                          'order' => '10',
                          'table_name' => 'patient_conditions',
                          'func_action' => 'delete',
                          'func_type' => 3,
                          'allowed_roles' => "[1]",
                          'status' => 'a',
                          'created_at' => date('Y-m-d H:i:s')
                      ],
                      [
                          'function_name' => 'create patient allergy',
                          'function_description' => 'create patient allergy',
                          'slugs' => 'add-patient-allergy',
                          'name_on_class' => 'add',
                          'page_title' => 'create a patient allergy',
                          'module_id' => '3',
                          'link_icon' => '',
                          'order' => '11',
                          'table_name' => 'patient_allergies',
                          'func_action' => 'add',
                          'func_type' => 3,
                          'allowed_roles' => "[1]",
                          'status' => 'a',
                          'created_at' => date('Y-m-d H:i:s')
                      ],
                      [
                          'function_name' => 'list of patient allergies',
                          'function_description' => 'patients',
                          'slugs' => 'list-patient-allergy',
                          'name_on_class' => 'index',
                          'page_title' => 'list of patients allergies',
                          'module_id' => '3',
                          'link_icon' => '<i class="fas fa-users"></i>',
                          'order' => '12',
                          'table_name' => 'patient_allergies',
                          'func_action' => 'link',
                          'func_type' => 2,
                          'allowed_roles' => "[1]",
                          'status' => 'a',
                          'created_at' => date('Y-m-d H:i:s')
                      ],
                      [
                          'function_name' => 'edit patient allergy',
                          'function_description' => 'edit patient allergy',
                          'slugs' => 'edit-patient-allergy',
                          'name_on_class' => 'edit',
                          'page_title' => 'edit patient allergy',
                          'module_id' => '3',
                          'link_icon' => '',
                          'order' => '13',
                          'table_name' => 'patient_allergies',
                          'func_action' => 'edit',
                          'func_type' => 3,
                          'allowed_roles' => "[1]",
                          'status' => 'a',
                          'created_at' => date('Y-m-d H:i:s')
                      ],
                      [
                          'function_name' => 'delete patient allergy',
                          'function_description' => 'delete patient allergy',
                          'slugs' => 'delete-patient-allergy',
                          'name_on_class' => 'delete',
                          'page_title' => 'delete patient allergy',
                          'module_id' => '3',
                          'link_icon' => '',
                          'order' => '14',
                          'table_name' => 'patient_allergies',
                          'func_action' => 'delete',
                          'func_type' => 3,
                          'allowed_roles' => "[1]",
                          'status' => 'a',
                          'created_at' => date('Y-m-d H:i:s')
                      ],
                      [
                          'function_name' => 'create patient relative',
                          'function_description' => 'create patient relative',
                          'slugs' => 'add-patient-relative',
                          'name_on_class' => 'add',
                          'page_title' => 'create a patient relative',
                          'module_id' => '3',
                          'link_icon' => '',
                          'order' => '15',
                          'table_name' => 'patient_relatives',
                          'func_action' => 'add',
                          'func_type' => 3,
                          'allowed_roles' => "[1]",
                          'status' => 'a',
                          'created_at' => date('Y-m-d H:i:s')
                      ],
                      [
                          'function_name' => 'list of patient relatives',
                          'function_description' => 'patients',
                          'slugs' => 'list-patient-relative',
                          'name_on_class' => 'index',
                          'page_title' => 'list of patients relatives',
                          'module_id' => '3',
                          'link_icon' => '<i class="fas fa-users"></i>',
                          'order' => '16',
                          'table_name' => 'patient_relatives',
                          'func_action' => 'link',
                          'func_type' => 2,
                          'allowed_roles' => "[1]",
                          'status' => 'a',
                          'created_at' => date('Y-m-d H:i:s')
                      ],
                      [
                          'function_name' => 'edit patient relative',
                          'function_description' => 'edit patient relative',
                          'slugs' => 'edit-patient-relative',
                          'name_on_class' => 'edit',
                          'page_title' => 'edit patient relative',
                          'module_id' => '3',
                          'link_icon' => '',
                          'order' => '17',
                          'table_name' => 'patient_relatives',
                          'func_action' => 'edit',
                          'func_type' => 3,
                          'allowed_roles' => "[1]",
                          'status' => 'a',
                          'created_at' => date('Y-m-d H:i:s')
                      ],
                      [
                          'function_name' => 'delete patient relative',
                          'function_description' => 'delete patient relative',
                          'slugs' => 'delete-patient-relative',
                          'name_on_class' => 'delete',
                          'page_title' => 'delete patient relative',
                          'module_id' => '3',
                          'link_icon' => '',
                          'order' => '18',
                          'table_name' => 'patient_relatives',
                          'func_action' => 'delete',
                          'func_type' => 3,
                          'allowed_roles' => "[1]",
                          'status' => 'a',
                          'created_at' => date('Y-m-d H:i:s')
                      ],
                      [
                          'function_name' => 'create attachment',
                          'function_description' => 'create attachment',
                          'slugs' => 'add-attachment',
                          'name_on_class' => 'add',
                          'page_title' => 'create a attachment',
                          'module_id' => '3',
                          'link_icon' => '',
                          'order' => '19',
                          'table_name' => 'attachments',
                          'func_action' => 'add',
                          'func_type' => 3,
                          'allowed_roles' => "[1]",
                          'status' => 'a',
                          'created_at' => date('Y-m-d H:i:s')
                      ],
                      [
                          'function_name' => 'list of attachments',
                          'function_description' => 'patients',
                          'slugs' => 'list-attachment',
                          'name_on_class' => 'index',
                          'page_title' => 'list of patients relatives',
                          'module_id' => '3',
                          'link_icon' => '<i class="fas fa-users"></i>',
                          'order' => '20',
                          'table_name' => 'attachments',
                          'func_action' => 'link',
                          'func_type' => 2,
                          'allowed_roles' => "[1]",
                          'status' => 'a',
                          'created_at' => date('Y-m-d H:i:s')
                      ],
                      [
                          'function_name' => 'edit attachment',
                          'function_description' => 'edit attachment',
                          'slugs' => 'edit-attachment',
                          'name_on_class' => 'edit',
                          'page_title' => 'edit attachment',
                          'module_id' => '3',
                          'link_icon' => '',
                          'order' => '21',
                          'table_name' => 'attachments',
                          'func_action' => 'edit',
                          'func_type' => 3,
                          'allowed_roles' => "[1]",
                          'status' => 'a',
                          'created_at' => date('Y-m-d H:i:s')
                      ],
                      [
                          'function_name' => 'delete attachment',
                          'function_description' => 'delete attachment',
                          'slugs' => 'delete-attachment',
                          'name_on_class' => 'delete',
                          'page_title' => 'delete attachment',
                          'module_id' => '3',
                          'link_icon' => '',
                          'order' => '22',
                          'table_name' => 'attachments',
                          'func_action' => 'delete',
                          'func_type' => 3,
                          'allowed_roles' => "[1]",
                          'status' => 'a',
                          'created_at' => date('Y-m-d H:i:s')
                      ],
                      [
                          'function_name' => 'create diagnosis',
                          'function_description' => 'create diagnosis',
                          'slugs' => 'add-diagnosis',
                          'name_on_class' => 'add',
                          'page_title' => 'create a diagnosis',
                          'module_id' => '3',
                          'link_icon' => '',
                          'order' => '19',
                          'table_name' => 'diagnosis',
                          'func_action' => 'add',
                          'func_type' => 3,
                          'allowed_roles' => "[1]",
                          'status' => 'a',
                          'created_at' => date('Y-m-d H:i:s')
                      ],
                      [
                          'function_name' => 'list of diagnosis',
                          'function_description' => 'patients',
                          'slugs' => 'list-diagnosis',
                          'name_on_class' => 'index',
                          'page_title' => 'list of patients relatives',
                          'module_id' => '3',
                          'link_icon' => '<i class="fas fa-users"></i>',
                          'order' => '20',
                          'table_name' => 'diagnosis',
                          'func_action' => 'link',
                          'func_type' => 2,
                          'allowed_roles' => "[1]",
                          'status' => 'a',
                          'created_at' => date('Y-m-d H:i:s')
                      ],
                      [
                          'function_name' => 'edit diagnosis',
                          'function_description' => 'edit diagnosis',
                          'slugs' => 'edit-diagnosis',
                          'name_on_class' => 'edit',
                          'page_title' => 'edit diagnosis',
                          'module_id' => '3',
                          'link_icon' => '',
                          'order' => '21',
                          'table_name' => 'diagnosis',
                          'func_action' => 'edit',
                          'func_type' => 3,
                          'allowed_roles' => "[1]",
                          'status' => 'a',
                          'created_at' => date('Y-m-d H:i:s')
                      ],
                      [
                          'function_name' => 'delete diagnosis',
                          'function_description' => 'delete diagnosis',
                          'slugs' => 'delete-diagnosis',
                          'name_on_class' => 'delete',
                          'page_title' => 'delete diagnosis',
                          'module_id' => '3',
                          'link_icon' => '',
                          'order' => '22',
                          'table_name' => 'diagnosis',
                          'func_action' => 'delete',
                          'func_type' => 3,
                          'allowed_roles' => "[1]",
                          'status' => 'a',
                          'created_at' => date('Y-m-d H:i:s')
                      ],
                      [
                          'function_name' => 'create visit',
                          'function_description' => 'create visit',
                          'slugs' => 'add-visit',
                          'name_on_class' => 'add',
                          'page_title' => 'create a visit',
                          'module_id' => '3',
                          'link_icon' => '',
                          'order' => '19',
                          'table_name' => 'visits',
                          'func_action' => 'add',
                          'func_type' => 3,
                          'allowed_roles' => "[1]",
                          'status' => 'a',
                          'created_at' => date('Y-m-d H:i:s')
                      ],
                      [
                          'function_name' => 'list of visits',
                          'function_description' => 'patients',
                          'slugs' => 'list-visit',
                          'name_on_class' => 'index',
                          'page_title' => 'list of patients relatives',
                          'module_id' => '3',
                          'link_icon' => '<i class="fas fa-users"></i>',
                          'order' => '20',
                          'table_name' => 'visits',
                          'func_action' => 'link',
                          'func_type' => 2,
                          'allowed_roles' => "[1]",
                          'status' => 'a',
                          'created_at' => date('Y-m-d H:i:s')
                      ],
                      [
                          'function_name' => 'edit visit',
                          'function_description' => 'edit visit',
                          'slugs' => 'edit-visit',
                          'name_on_class' => 'edit',
                          'page_title' => 'edit visit',
                          'module_id' => '3',
                          'link_icon' => '',
                          'order' => '21',
                          'table_name' => 'visits',
                          'func_action' => 'edit',
                          'func_type' => 3,
                          'allowed_roles' => "[1]",
                          'status' => 'a',
                          'created_at' => date('Y-m-d H:i:s')
                      ],
                      [
                          'function_name' => 'delete visit',
                          'function_description' => 'delete visit',
                          'slugs' => 'delete-visit',
                          'name_on_class' => 'delete',
                          'page_title' => 'delete visit',
                          'module_id' => '3',
                          'link_icon' => '',
                          'order' => '22',
                          'table_name' => 'visits',
                          'func_action' => 'delete',
                          'func_type' => 3,
                          'allowed_roles' => "[1]",
                          'status' => 'a',
                          'created_at' => date('Y-m-d H:i:s')
                      ],
                ];
                $db      = \Config\Database::connect();
                $builder = $db->table($this->table);
                $builder->insertBatch($data);
        }

        public function down()
        {
                // $this->forge->dropTable($this->table);
        }
}
